// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wekohmrtrrebcdprvzza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indla29obXJ0cnJlYmNkcHJ2enphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODg0MjcsImV4cCI6MjA2NDQ2NDQyN30.V0XnDzvCnDJqL9eaHwesZYJf0sKbCkyRAG27PTlZoJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);